services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    container_name: server-container

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3001:3001"
    depends_on:
      - server
    networks:
      - mynetwork
    container_name: client-container
networks:
  mynetwork:
    driver: bridge