# ./monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user_service'
    static_configs:
      - targets: ['user_service:5001']

  - job_name: 'shop_service'
    static_configs:
      - targets: ['shop_service:5002']

  - job_name: 'transaction_service'
    static_configs:
      - targets: ['transaction_service:5003']

  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:8000']

