apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-pvc
  namespace: marketplace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-userdb
  namespace: marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-userdb
  template:
    metadata:
      labels:
        app: postgres-userdb
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: user_db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-userdb-storage
      volumes:
      - name: postgres-userdb-storage
        persistentVolumeClaim:
          claimName: userdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-userdb
  namespace: marketplace
spec:
  selector:
    app: postgres-userdb
  ports:
    - protocol: TCP
      port: 5432
